import Head from 'next/head'
import * as animationData from './rocket.json'
import {FaWhatsapp,FaRocket} from "react-icons/fa";

export default function Home() {

    return (
        <div className={"flex flex-col items-center justify-between h-screen bg-gradient-to-b from-yellow-400 via-red-500 to-pink-500"}>
            <Head>
                <title>Suzy - Links</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;400;700&display=swap"
                      rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex grid grid-cols-12 gap-4 w-full">

                <aside
                    className="col-span-12 flex flex-col items-center justify-center relative">
                    <div className={"w-screen bg-gray-100 absolute h-1/2 top-0 z-0"}>

                    </div>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img className={"rounded-full w-40 mt-4 border-4 shadow-md border-white z-10"} src="suza.jpeg" alt=""/>
                    <h1 className={"text-white text-sm font-bold font-primary"}>@suzannasilva25</h1>

                </aside>
                <a
                    href={"https://edzz.la/S85IC?a=78113334"}
                    target={"_blank"}
                    className="mx-8 lg:mx-40 col-span-12 text-center bg-gray-200 shadow font-primary text-pink-900 hover:shadow-lg text-white text-sm font-medium py-3 px-4 rounded" rel="noreferrer">
                    Ebook Gratis - 5 formas garantidas para ganhar dinheiro online
                </a>
                <a
                    href={"https://api.whatsapp.com/send?phone=5583998936754&text=Oii%20Suzy%2C%20me%20ajuda%20a%20entender%20o%20*Mkt%20Digital*%3F"}
                    target={"_blank"}
                    className="mx-8 lg:mx-40 col-span-12 flex items-center justify-center bg-green-700 shadow hover:shadow-lg py-3 px-4 rounded" rel="noreferrer">
                    <FaWhatsapp className={"text-white  text-2xl"}/>
                    <span className={"font-primary text-white text-sm font-medium text-gray-100 ml-2"}>Dúvidas? Me chama no Whats</span>
                </a>
                <a
                    href={"https://api.whatsapp.com/send?phone=5583998936754&text=Oii%20Suzy%2C%20me%20explica%20sobre%20esse%20o%20*M%C3%A9todo%20Mulher%20Milionaria*%3F"}
                    target={"_blank"}
                    className="zoom-in-zoom-out mx-8 lg:mx-40 col-span-12 flex items-center justify-center bg-pink-800 shadow hover:shadow-lg py-3 px-4 rounded" rel="noreferrer">
                    <FaRocket className={"text-white text-2xl"}/>
                    <span className={"font-primary text-white text-sm text-center font-medium text-gray-100 ml-2"}>Treinamento Completo - Método Mulher Milionaria</span>
                </a>
                <footer className={"col-span-12 mt-10 font-primary flex flex-col items-center justify-center"}>
                    <b className={"text-sm"}>Construido por</b>
                    <a
                        href={"https://www.instagram.com/mateusxsuzana.py/"}
                        target={"_blank"}
                        className={"text-sm"} rel="noreferrer">
                        @mateusxsuzana.py
                    </a>
                </footer>
            </main>
        </div>
    )
}
